name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Wasm Target
      run: rustup target add wasm32-unknown-unknown
    - name: Install trunk
      run: cargo install trunk
    - name: Build
      run: trunk build --release --dist ./docs ./yew-app/index.html
