name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup
      run: |
        rustup target add wasm32-unknown-unknown
        cargo install trunk
    - name: Build
      run: trunk build --release --public-url /rust-connect-four/ --dist ./docs ./yew-app/index.html
    - name: Check for Changes
      run: git status
    - name: Commit Changes
      run: |
        git config --local user.name "deploy-bot"
        git add ./docs
        git commit -m "Auto build target."
    - name: Push Changes
      run: git push
